'use client'

import { useState, useEffect, useRef } from 'react'
import { subscribeToEvents } from '@/lib/realtime/channels'
import { GameEvent } from '@/types'
import { motion, AnimatePresence } from 'framer-motion'

interface ActivityFeedProps {
  initialEvents: GameEvent[]
}

export default function ActivityFeed({ initialEvents }: ActivityFeedProps) {
  const [events, setEvents] = useState<GameEvent[]>(initialEvents)
  const feedEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    // Keep feed scrolled to top or auto-scroll
    const channel = subscribeToEvents((payload) => {
      const newEvent = payload.new as GameEvent
      
      // Skip broadcasts or internal end events from the public feed
      if (newEvent.metadata?.isBroadcast || newEvent.metadata?.isEndEvent) return

      setEvents((prev) => [newEvent, ...prev].slice(0, 50)) // Keep last 50 events
    })
    return () => { channel.unsubscribe() }
  }, [])

  const formatMessage = (ev: GameEvent) => {
    const t = ev.metadata?.teamName || 'A team'
    const s = ev.metadata?.secondaryTeamName
    
    switch (ev.event_type) {
      case 'stage_completed': return `${t} completed stage ${ev.metadata?.stage?.toUpperCase()}`
      case 'phone_usage': return `📵 ${t} was caught using phone`
      case 'manual_deduction': return `⚖️ ${t} was penalized`
      case 'hint_given': return `💡 Hint issued to ${t}`
      case 'task_changed': return `🔄 Task re-rolled for ${t}`
      case 'sabotage_sold': return `💣 ${t} acquired a sabotage`
      case 'sabotage_used': return `❄️ ${t} froze ${s}!`
      case 'token_increase': return `⬆️ ${t} earned tokens`
      case 'skip_task': return `⏭️ Task skipped for ${t}`
      case 'admin_token_change': return `⚙️ ${t} tokens manually adjusted`
      default: return `Event generated by ${ev.triggered_by_role.replace('_', ' ')}`
    }
  }

  return (
    <div className="card h-[400px] flex flex-col overflow-hidden relative border-accent-primary/10">
      {/* Header */}
      <div className="p-4 border-b border-white/[0.04] bg-white/[0.01] flex items-center gap-3 relative z-10 shrink-0">
        <div className="w-2 h-2 rounded-full bg-accent-glow animate-pulse" />
        <h3 className="font-display font-bold text-sm text-secondary tracking-wider uppercase">Live Activity Feed</h3>
      </div>
      
      {/* Feed List */}
      <div className="flex-1 overflow-y-auto p-4 space-y-3 custom-scrollbar relative z-10">
        <AnimatePresence initial={false}>
          {events.length === 0 ? (
            <p className="text-center text-muted text-sm my-10">Listening for activity...</p>
          ) : (
            events.map((ev) => (
              <motion.div
                key={ev.id}
                initial={{ opacity: 0, height: 0, x: -20 }}
                animate={{ opacity: 1, height: 'auto', x: 0 }}
                className="bg-white/[0.02] border border-white/[0.02] rounded-lg p-3 text-sm flex gap-3"
              >
                <div className="mt-1 opacity-50 text-[10px] uppercase font-mono tracking-wider w-12 shrink-0">
                  {new Date(ev.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </div>
                <div className="flex-1">
                  <p className="text-primary leading-snug">{formatMessage(ev)}</p>
                  {ev.token_delta !== 0 && ev.token_delta !== null && (
                    <span className={`inline-block mt-1 text-xs font-mono font-bold ${ev.token_delta > 0 ? 'text-accent-finish' : 'text-accent-danger'}`}>
                      {ev.token_delta > 0 ? '+' : ''}{ev.token_delta} equity
                    </span>
                  )}
                </div>
              </motion.div>
            ))
          )}
        </AnimatePresence>
        <div ref={feedEndRef} />
      </div>
      
      {/* Bottom fade out gradient */}
      <div className="absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-t from-base to-transparent pointer-events-none z-20" />
    </div>
  )
}
